server {
    listen 80;
    server_name modysolutions.com;

    root /var/www/html;
    index index.php index.html index.htm;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_read_timeout 300s;
    }

    location ~ /\.ht {
        deny all;
    }
    location ~ /wp-content/uploads/.*\.php$ {
        deny all;
    }
    location ~ /wp-config.php {
        deny all;
    }
    location ~ /xmlrpc.php {
        deny all;
    }
}
