services:
  wordpress:
    build: .
    container_name: ${SITE_SLUG}_wordpress_fpm
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php-conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_CONFIG_EXTRA: "define('WP_ENVIRONMENT_TYPE', 'production');"
      WORDPRESS_REDIS_HOST: redis
      WORDPRESS_REDIS_PORT: 6379
      WORDPRESS_REDIS_PASSWORD: $WORDPRESS_REDIS_PASSWORD
      WORDPRESS_REDIS_DATABASE: 0
      PUID: 1001
      PGID: 1001
      TZ: Europe/Madrid

    depends_on:
      - db
      - redis
    networks:
      - internal_site_network

  nginx:
    image: nginx:stable-alpine
    container_name: ${SITE_SLUG}_nginx
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress
    networks:
      - internal_site_network

  db:
    image: mariadb:11.4.7
    container_name: ${SITE_SLUG}_mariadb
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mariadb-conf/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WORDPRESS_DB_USER
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD
      TZ: Europe/Madrid
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal_site_network
  redis:
    image: redis:6-alpine
    container_name: ${SITE_SLUG}_redis
    restart: unless-stopped
    volumes:
      - ./redis_data:/data
    command: redis-server --requirepass ""

networks:
  mody_cloud_network:
    external: true

  internal_site_network:
    driver: bridge
