services:
  wordpress:
    image: wordpress:fpm
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./html:/var/www/html
      - ./config/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_CONFIG_EXTRA: $WORDPRESS_CONFIG_EXTRA
      TZ: $TIMEZONE
    networks:
      - internal_site_network

    depends_on:
      db:
        condition: service_healthy

  webserver:
    image: nginx:stable-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./html:/var/www/html:ro
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      wordpress:
        condition: service_started
    networks:
      - internal_site_network

  db:
    image: mariadb:11.4.7
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./db_data:/var/lib/mysql
      - ./config/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      MARIADB_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: $TIMEZONE
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - internal_site_network

networks:
  internal_site_network:
    driver: overlay
    attachable: true